#!/bin/bash

RTCDIR="${HOME}/Real-Time-Control"
cd ${RTCDIR}


# ==============================================================
# Deploy RTC scripts
# ==============================================================

cd scexaoRTCconf
./confinstall
cd ..

source ~/.profile

mkdir -p scexaoRTCsoft






# COMPILE EXECUTABLES
cd scexaoRTCbin

# compile and install setlatency executable
gcc -o setlatency ${RTCDIR}/scexaoRTCprogs/setlatency/setlatency.c

# ==============================================================
# NETWORK
# ==============================================================

sudo cp ${RTCDIR}/scexaoRTCconf/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml
sudo netplan apply

# to check hardware interfaces:
# sudo lshw -class network -businfo

# Bus info          Device     Class          Description
# =======================================================
# pci@0000:01:00.0  enp1s0f0   network        Ethernet Controller 10G X550T
# pci@0000:01:00.1  enp1s0f1   network        Ethernet Controller 10G X550T
# pci@0000:1b:00.0  enp27s0f0  network        82599ES 10-Gigabit SFI/SFP+ Network Connection
# pci@0000:1b:00.1  enp27s0f1  network        82599ES 10-Gigabit SFI/SFP+ Network Connection
# pci@0000:86:00.0  ens4f0     network        MT27700 Family [ConnectX-4]
# pci@0000:86:00.1  ens4f1     network        MT27700 Family [ConnectX-4]
# pci@0000:db:00.0             network        MT27800 Family [ConnectX-5]
# pci@0000:db:00.1             network        MT27800 Family [ConnectX-5]






# ==============================================================
# STORAGE DRIVES
# ==============================================================

# create directories
cd /mnt

sudo mkdir sdata00
sudo chown scexao sdata00/
sudo chgrp scexao sdata00/

sudo mkdir md0
sudo chown scexao md0/
sudo chgrp scexao md0/

cd ${RTCDIR}/scexaoRTCconf/
cat /etc/fstab fstabadd > fstab.new
cp /etc/fstab fstab.old
sudo cp fstab.new /etc/fstab

sudo mount /mnt/md0
sudo mount /mnt/sdata00




# ==============================================================
# REMOTE ACCESS, misc tools
# ==============================================================

# x2go
sudo apt install -y x2goserver
sudo apt install -y --no-install-recommends lxde
sudo apt install -y terminator

# To increase number of desktops etc...
sudo apt install -y wmctrl


# Misc convenience and tools
sudo apt install -y geany gparted iotop numactl saods9



# ==============================================================
# DM driver
# ==============================================================

cd $HOME
mkdir -p src/DMoptical
cd src/DMoptical
rsync -au --progress /home/scexao/Real-Time-Control/scexaoRTCprogs/DMoptical/* .

# content was uncompressed by:
# tar -jxvf bmc_linux_sdk_2.2.tbz2
# Note: List of changes made to source code:

# In drv/bmc_mdrv.c
#- #include <asm/uaccess.h>
#+ #include <linux/uaccess.h>

#In drv/bmc_mdrv.c
#- #include <sys/ioctl.h>
#+ #include <linux/ioctl.h>

#In drv/bmc_mdrv.c
#+ #include <linux/uaccess.h>

#In lib/bmc_mdlib.c
#- #include <linux/ioctl.h>
#+ #include <sys/ioctl.h>

#In tool/bmc_ltest.c
+ #include <sys/time.h>

#Compile and install:

mkdir -p tmp
mkdir -p lib
cd src
make
cd ../bin
sudo insmod bmc_mdrv.ko
sudo chmod o+rw /dev/bmc_mdrv*

# ==============================================================
# KICK IN A PYTHON INSTALL (/home/scexao/anaconda3)
# ==============================================================

cd $HOME && mkdir -p os_install && cd os_install
wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
bash Anaconda3-2020.02-Linux-x86_64.sh 

echo -e "\n# Anaconda3" >> $HOME/.profile_scexaoRTC
echo "export PATH=\$HOME/miniconda3/bin:\$PATH"  >> $HOME/.profile_scexaoRTC
source ../.profile


# ==============================================================
# CONFIGURE CACAO 
# ==============================================================

# Now we need milk and cacao
## MILK

cd $HOME/src
git clone --recursive https://www.github.com/milk-org/milk-package.git milk
cd milk
# git checkout dev
git submodule update
pip install pybind11
./compile.sh

echo -e "\n# MILK package" >> $HOME/.profile_scexaoRTC
echo "export MILK_SHM_DIR=/milk/shm" >> $HOME/.profile_scexaoRTC
echo "export MILK_ROOT=\$HOME/src/milk" >> $HOME/.profile_scexaoRTC
echo "export MILK_INSTALLDIR=/usr/local/milk" >> $HOME/.profile_scexaoRTC
echo "export PATH=\$PATH:\$MILK_INSTALLDIR/bin" >> $HOME/.profile_scexaoRTC
echo "export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH:\$MILK_INSTALLDIR/lib/pkgconfig" >> $HOME/.profile_scexaoRTC
source $HOME/.profile

echo "/usr/local/magma/lib" > magma.conf
sudo mv magma.conf /etc/ld.so.conf.d/
sudo ldconfig -v

# Make the tmpfs disk
echo "tmpfs /milk/shm tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
sudo mkdir -p /milk/shm
sudo mount /milk/shm

## pyMilk

cd $HOME/src
git clone https://www.github.com/milk-org/pyMilk.git pyMilk
cd pyMilk
pip install -e .
echo -e "\n# pyMILK python package" >> $HOME/.profile_scexaoRTC
echo "export PYTHONPATH=\$MILK_INSTALLDIR/python:\$PYTHONPATH" >> $HOME/.profile_scexaoRTC
source $HOME/.profile

## CACAO

cd $HOME/src
git clone --recursive https://github.com/cacao-org/cacao cacao
cd cacao
# git checkout dev-v1.01
git submodule update
./compile.sh
echo -e "\n# CACAO package" >> $HOME/.profile_scexaoRTC
echo "export CACAO_ROOT=\$HOME/src/cacao" >> $HOME/.profile_scexaoRTC
echo "export CACAO_INSTALLDIR=/usr/local/cacao" >> $HOME/.profile_scexaoRTC
echo "export PATH=\$PATH:\$CACAO_INSTALLDIR/bin" >> $HOME/.profile_scexaoRTC
source $HOME/.profile


