#!/bin/bash

RTCDIR="${HOME}/Real-Time-Control"


# REMOTE ACCESS

# x2go

sudo apt install -y x2goserver
sudo apt install -y --no-install-recommends lxde
sudo apt install -y terminator

# To increase number of desktops etc...
sudo apt install -y wmctrl



# Misc convenience

sudo apt install -y geany





cd ${HOME}
mkdir -p scexaoRTCbin
mkdir -p scexaoRTCsoft


# add entries to .profile
cp ${RTCDIR}/scexaoRTCconf/profile ${HOME}/.profile_scexaoRTC
source ~/.profile


cd scexaoRTCbin

# compile and install setlatency executable
gcc -o setlatency ${RTCDIR}/scexaoRTCprogs/setlatency/setlatency.c




# CACAO 

cd ${HOME}
sudo apt-get install -y cmake flex bison pkg-config
sudo apt-get install -y libcfitsio7 libcfitsio-dev libreadline-dev libfftw3-dev libgsl-dev libncurses5-dev 

mkdir -p src
cd src
git clone --recursive https://github.com/cacao-org/cacao cacao
cd cacao
git submodule foreach "(git checkout dev; git pull)"
git checkout dev; git pull
mkdir _build
cd _build
cmake ..
sudo make install
sudo ln -s /usr/local/bin/cacao /usr/local/bin/milk

# post installation

echo "/usr/local/lib" > usrlocal.conf
sudo mv usrlocal.conf /etc/ld.so.conf.d/
sudo ldconfig -v


echo "tmpfs /milk/shm tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
sudo mkdir -p /milk/shm
sudo mount /milk/shm

