#!/bin/bash

TelemetryDirectory="$1"
StreamName1=$2
StreamName2=$3
StartTime=$4
EndTime=$5
dT=$6
lagT=$7

cacao << EOF
aolptmksyncs2 "${TelemetryDirectory}" ${StreamName1} ${StreamName2} ${StartTime} ${EndTime} ${dT} ${lagT}
savefits outC0 "!${StreamName1}.fits"
savefits outC1 "!${StreamName2}.fits"
listim
exitCLI
EOF
mv exptime.dat exptime.${StreamName1}.${StreamName2}.dat

