#
#	Makefile				Boston Micromachines Corp. mirror driver makefile
#
#	Oct 20,     2014        CIW/SJT original entry
#
#	© Copyright 2014, Boston Micromachines, Inc. All rights reserved.
#
###
#
EXTRA_CFLAGS	+= -I$(PWD)/../inc
obj-m := bmc_mdrv.o

