#!/bin/bash

# Run this script in the telemetry directory
# 

for dir in 202010*
do

YRstring=${dir:0:4}
MOstring=${dir:4:2}
DYstring=${dir:6:2}

UTdatestring="${YRstring}/${MOstring}/${DYstring}"

if [ -d $dir ]; then

# Get RTC log from AOloop0 directory
echo "Pulling logs for directory $dir   ${UTdatestring} --- ${YRstring}  ${MOstring}  ${DYstring}"
mkdir -p ${dir}/logdir/
cp ~/AOloop/AOloop0/logdir/${dir}/logging/* ./${dir}/logdir/

# Get instrument logs
rsync -au --progress scexao@scexao2:/media/data/${dir}/logging/* ./${dir}/logdir/

# Get DIMM seeing measurement
wget http://mkwc.ifa.hawaii.edu/current/seeing/dimm/${dir}.dimm.dat -O tmp.dat
awk '{printf("%s %02d:%02d:%02d MKODIMMseeing %s\n", "'$UTdatestring'", ($4+10)%24,$5,$6,$7)}' tmp.dat > seeing.dimm.dat
mv seeing.dimm.dat ./${dir}/logdir/${dir}.seeing.dimm.dat

# Get MASS seeing measurement
wget http://mkwc.ifa.hawaii.edu/current/seeing/mass/${dir}.mass.dat -O tmp.dat
awk '{printf("%s %02d:%02d:%02d MKOMASSseeing %s\n", "'$UTdatestring'", ($4+10)%24,$5,$6,$7)}' tmp.dat > seeing.mass.dat
mv seeing.mass.dat ./${dir}/logdir/${dir}.seeing.mass.dat

# Get MASS profile measurement
wget http://mkwc.ifa.hawaii.edu/current/seeing/masspro/${dir}.masspro.dat -O tmp.dat
awk '{printf("%s %02d:%02d:%02d MKOMASSseeing %s %s %s %s %s %s %s\n", "'$UTdatestring'", ($4+10)%24,$5,$6, $7,$8,$9,$10,$11,$12,$13)}' tmp.dat > seeing.masspro.dat
mv seeing.masspro.dat ./${dir}/logdir/${dir}.seeing.masspro.dat



else
  echo "Directory ${dir} does not exist"
fi

done

