#!/bin/bash

# Run this script in the telemetry directory
# 

for dir in 202010*
do

YRstring=${dir:0:4}
MOstring=${dir:4:2}
DYstring=${dir:6:2}

UTdatestring="${YRstring}/${MOstring}/${DYstring}"

if [ -d $dir ]; then

# Get RTC log from AOloop0 directory
echo "Pulling logs for directory $dir   ${UTdatestring} --- ${YRstring}  ${MOstring}  ${DYstring}"
mkdir -p ${dir}/logdir/
cp ~/AOloop/AOloop0/logdir/${dir}/logging/* ./${dir}/logdir/

# Get instrument logs
rsync -au --progress scexao@scexao2:/media/data/${dir}/logging/* ./${dir}/logdir/

# Get DIMM seeing measurement
wget http://mkwc.ifa.hawaii.edu/current/seeing/dimm/${dir}.dimm.dat -O tmp.dat
awk '{printf("%04d %02d %02d %02d:%02d:%02d MKDIMMseeing %s\n", $YRstring, $MOstring, $DYstring, ($4+10)%24,$5,$6,$7)}' tmp.dat > seeing.dimm.dat
mv seeing.dimm.dat ./${dir}/logdir/${dir}.seeing.dimm.dat

else
  echo "Directory ${dir} does not exist"
fi

done

