#!/bin/bash

cd $HOME/src
git clone --recursive https://github.com/cacao-org/cacao cacao
cd cacao
git submodule update
git branch --list
read -p "Use branch dev (no for branch name)? [y/n]: " YESNOTMP
if [ $YESNOTMP = "y" ]; then
    git checkout dev
    git submodule update
else        
    read -p "Which branch (empty for master)? " CACAO_BRANCH
    if [ $CACAO_BRANCH ]; then
        git checkout $CACAO_BRANCH
        git submodule update
    fi
fi
read -p "Pull submodules to latest? [y/n]: " YESNOTMP
if [ $YESNOTMP = "y" ]; then
    git checkout dev
    git submodule foreach "(git checkout dev; git pull)"
fi

echo "Compiling and installing CACAO"
./compile.sh
echo -e "\n# CACAO package" >> $HOME/.profile_scexaoRTC
echo "export CACAO_ROOT=\$HOME/src/cacao" >> $HOME/.profile_scexaoRTC
echo "export CACAO_INSTALLDIR=/usr/local/cacao" >> $HOME/.profile_scexaoRTC
echo "export PATH=\$PATH:\$CACAO_INSTALLDIR/bin" >> $HOME/.profile_scexaoRTC
source $HOME/.profile

echo "Gathering cacao-* binaries in src/cacao/bin..."
mkdir -p bin && cd bin
find . -executable -type f -name "cacao-*" -print0 | xargs -0 -I {} ln -s {} .
cd ..
