#ifndef DPIODEFS_H
#define DPIODEFS_H


typedef enum
{

  DPIO_DMA_DONE_INTERRUPT = 0,
  DPIO_FIFO_NOT_EMPTY_INTERRUPT,
  DPIO_FIFO_EMPTY_INTERRUPT,
  DPIO_FIFO_HALF_FULL_INTERRUPT,
  DPIO_FIFO_FULL_INTERRUPT,
  DPIO_PIO1_ASSERTED_INTERRUPT,
  DPIO_PIO2_ASSERTED_INTERRUPT,
  DPIO_FIFO_LOCK_INTERRUPT,
  DPIO_PCI_ABORT_INTERRUPT,
  DPIO_NEXT_FREE_INTERRUPT_SOURCE_ID

} DPIO_INTERRUPT_SOURCE_ID;


typedef enum
{

  DPIO_NOTHING_MARKS_EOT      = 0,
  DPIO_PIO2_MARKS_EOT         = 1,
  DPIO_RES1_OR_SYNC_MARKS_EOT = 2,
  DPIO_PIO1_MARKS_EOT         = 3

} DPIO_END_OF_TRANSFER_MODE;


typedef enum
{

  DPIO_START_FIFO_GTHF_PAUSE_FIFO_E    = 0,
  DPIO_START_FIFO_AF_PAUSE_FIFO_E      = 1,
  DPIO_START_FIFO_F_PAUSE_FIFO_E       = 2,
  DPIO_START_FIFO_GTHF_PAUSE_FIFO_AE   = 3,
  DPIO_START_FIFO_AF_PAUSE_FIFO_AE     = 4,
  DPIO_START_FIFO_F_PAUSE_FIFO_AE      = 5,
  DPIO_START_FIFO_LTHF_PAUSE_FIFO_AE   = 6,
  DPIO_START_FIFO_GTHF_PAUSE_ON_SIGNAL = 7

} DPIO_INPUT_DMA_DEMAND_MODE;


typedef enum
{

  DPIO_PAUSE_FIFO_GTHF_START_FIFO_E  = 0,
  DPIO_PAUSE_FIFO_AF_START_FIFO_E    = 1,
  DPIO_PAUSE_FIFO_F_START_FIFO_E     = 2,
  DPIO_PAUSE_FIFO_GTHF_START_FIFO_AE = 3,
  DPIO_PAUSE_FIFO_AF_START_FIFO_AE   = 4,
  DPIO_PAUSE_FIFO_F_START_FIFO_AE    = 5

} DPIO_OUTPUT_DMA_DEMAND_MODE;


#define  DPIO_DMA_CONTROL_REGISTER_ENABLE_D0_AS_SYNC_BITMASK         (0x80)
#define  DPIO_DMA_CONTROL_REGISTER_SIGNAL_DEMAND_MODE_PAUSE_BITMASK  (0x80)
#define  DPIO_DMA_CONTROL_REGISTER_ENABLE_END_OF_FRAME_SYNC_BITMASK  (0x40)
#define  DPIO_DMA_CONTROL_REGISTER_DEMAND_MODE_BITMASK               (0x07)

#endif /* DPIODEFS_H */




